services:
  - type: web
    name: backend-ans-intuitive
    env: python
    buildCommand: cd PARTE4/backend && pip install -r requirements.txt
    startCommand: cd PARTE4/backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
